# Generated by Django 4.0.4 on 2022-04-25 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_description_remove_user_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='written_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='has_written', to=settings.AUTH_USER_MODEL),
        ),
    ]
