# Generated by Django 3.2.9 on 2022-04-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_comment_in_response_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
