# Generated by Django 3.2.9 on 2022-04-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_an_user', 'can create an user'), ('can_read_an_user', 'can read an user'), ('can_update_an_user', 'can update user'), ('can_delete_an_user', 'can delete an user')]},
        ),
    ]
