# Generated by Django 3.2.9 on 2022-04-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options'),
    ]

    operations = [
        migrations.RunSQL(
        'ALTER SEQUENCE users_user_id_seq RESTART WITH 2;'
    )
    ]
