# Generated by Django 3.2.9 on 2022-04-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220425_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_user', 'can create user'), ('can_read_user', 'can read user'), ('can_update_user', 'can update user'), ('can_delete_user', 'can delete user')]},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'superuser'), (2, 'organization admin'), (3, 'organization member'), (4, 'project owner'), (5, 'project member')], default=5),
        ),
    ]
