# Generated by Django 3.2.9 on 2022-04-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_user', 'can create user'), ('can_create_superuser', 'can create superuser'), ('can_read_user', 'can read user'), ('can_update_user', 'can update user'), ('can_delete_user', 'can delete user')]},
        ),
    ]
