# Generated by Django 3.2.9 on 2022-04-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_a_superuser', 'can create a super user'), ('can_read_user', 'can read user'), ('can_update_user', 'can update user'), ('can_delete_user', 'can delete user')]},
        ),
    ]
