# Generated by Django 3.2.9 on 2022-04-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_a_superuser', 'can create a super user'), ('can_create_an_org_admin', 'can create an org admin'), ('can_create_an_project_owner', 'can create an org admin'), ('can_create_an_org_member', 'can create an org member'), ('can_create_an_project_member', 'can create an project member'), ('can_read_user', 'can read user'), ('can_update_user', 'can update user'), ('can_delete_user', 'can delete user')]},
        ),
    ]
