# Generated by Django 3.2.9 on 2022-04-28 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.CharField(choices=[(0, 'No poverty'), (1, 'Zero hunger'), (2, 'Good health and well-being'), (3, 'Quality education'), (4, 'Gender equality'), (5, 'Clean water and sanitation'), (6, 'Affordable and clean energy'), (7, 'Decent work and economic growth'), (8, 'Industry, innovation, and infrastructure'), (9, 'Reduces inequalities'), (10, 'Sustainable cities and communities'), (11, 'Responsible consumption & production'), (12, 'Climate action'), (13, 'Life below water'), (14, 'Life on land'), (15, 'Peace, justice, and strong institutions')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
