# Generated by Django 3.2.9 on 2022-04-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('can_create_an_organization', 'As a user I can create an organization'), ('can_read_all_the_organization', 'As a user I can read all the organization'), ('can_update_organization', 'As a user I can update my organization'), ('can_delete_organization', 'As a user I can delete my organization')]},
        ),
    ]
