# Generated by Django 3.2.9 on 2022-05-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_options'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE organizations_organization_id_seq RESTART WITH 2;'
        )
    ]