# Generated by Django 3.2.9 on 2022-04-27 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('text', models.CharField(max_length=280)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('in_response_to', models.ForeignKey(blank=True, null=True, on_delete=models.SET(users.models.get_placeholder_for_deleted_comment), to='comments.comment')),
                ('written_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='has_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_create_a_comment', 'As a user I can publish a comment'), ('can_read_all_the_comments', 'As a user I can read all the comments'), ('can_update_comments', 'As a user I can update my comments'), ('can_delete_comment', 'As a user I can delete my tweet')],
            },
        ),
    ]
