# Generated by Django 3.2.9 on 2022-04-27 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='in_response_to',
            field=models.ForeignKey(blank=True, db_column='in_response_to', null=True, on_delete=models.SET(users.models.get_placeholder_for_deleted_comment), to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='written_by',
            field=models.ForeignKey(db_column='written_by', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='has_written', to=settings.AUTH_USER_MODEL),
        ),
    ]
