# Generated by Django 3.2.9 on 2022-04-28 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20220427_0740'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE comments_comment_id_seq RESTART WITH 2;'
        )
    ]
