# Generated by Django 3.2.9 on 2022-04-28 07:33

import comments.models
from django.conf import settings
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_auto_20220428_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='in_response_to',
            field=models.ForeignKey(blank=True, db_column='in_response_to', null=True, on_delete=models.SET(comments.models.get_placeholder), to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='written_by',
            field=models.ForeignKey(db_column='written_by', default=1, on_delete=models.SET(users.models.get_placeholder_for_deleted_comment), related_name='has_written', to=settings.AUTH_USER_MODEL),
        ),
    ]
